version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: shop-jenkins
    user: root # 도커 내부에서 권한 문제 방지
    ports:
      - "9090:8080" # 스프링 부트(8080)와 충돌하지 않도록 젠킨스는 9090 포트 사용
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # 윈도우 환경과 시간대를 맞추기 위한 설정 (옵션)
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Seoul
    restart: on-failure

  redis:
    image: redis:7-alpine
    container_name: shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: shop-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: shop-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: on-failure

volumes:
  jenkins_data:
  redis_data:
  es_data:
