spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace
